### ISSUE TITLE
fails to build with ghc-9.4 for Stackage Nightly

### ISSUE THREAD

**Issue by juhp** [trskop/connection-pool#2]
```
Building library for connection-pool-0.2.2..                                                                            [201/182284]
[5 of 9] Compiling Data.ConnectionPool.Internal.ConnectionPool                                                                      

/var/stackage/work/unpack-dir/unpacked/connection-pool-0.2.2-59172d8e2bc6c82e06991a9601f932ad6f3dfd0348cea0cce0ae60b16dc54ebd/src/Da
ta/ConnectionPool/Internal/ConnectionPool.hs:96:56: error:
    • Could not deduce (Show (Pool (c, i)))                       
        arising from a use of ‘shows’                             
      from the context: Show handlerParams                        
        bound by the instance declaration                         
        at src/Data/ConnectionPool/Internal/ConnectionPool.hs:94:10-70                                                              
    • In the first argument of ‘(.)’, namely ‘shows _resourcePool’                                                                  
      In the second argument of ‘(.)’, namely                                                                                       
        ‘shows _resourcePool                                      
           . showString ", handlerParams = "                                                                                        
               . shows _handlerParams . showChar '}'’                                                                               
      In the expression:                                          
        showString "ConnectionPool {resourcePool = "                                                                                
          . shows _resourcePool                                   
              . showString ", handlerParams = "                                                                                     
                  . shows _handlerParams . showChar '}'                                                                             
   |                                                              
96 |         showString "ConnectionPool {resourcePool = " . shows _resourcePool                                                     
   |                                                        ^^^^^                                                                   

/var/stackage/work/unpack-dir/unpacked/connection-pool-0.2.2-59172d8e2bc6c82e06991a9601f932ad6f3dfd0348cea0cce0ae60b16dc54ebd/src/Da
ta/ConnectionPool/Internal/ConnectionPool.hs:176:5: error:
    • Couldn't match type ‘m’ with ‘IO’                           
      Expected: m r                                               
        Actual: IO r                                              
      ‘m’ is a rigid type variable bound by                       
        the type signature for:                                   
          withConnection :: forall (m :: * -> *) handlerParams connection                                                           
                                   connectionInfo r.                                                                                
                            MonadBaseControl IO m =>                                                                                
                            ConnectionPool handlerParams connection connectionInfo                                                  
                            -> (handlerParams -> connection -> connectionInfo -> m r) -> m r
        at src/Data/ConnectionPool/Internal/ConnectionPool.hs:(170,1)-(174,10)                                                      
    • In the expression:                                          
        Pool.withResource _resourcePool (uncurry (f _handlerParams))                                                                
      In an equation for ‘withConnection’:                        
          withConnection ConnectionPool {..} f                                                                                      
            = Pool.withResource _resourcePool (uncurry (f _handlerParams))                                                          
    • Relevant bindings include                                                                                         [159/182284]
        f :: handlerParams -> connection -> connectionInfo -> m r                                                                   
          (bound at src/Data/ConnectionPool/Internal/ConnectionPool.hs:175:35)                                                      
        withConnection :: ConnectionPool                          
                            handlerParams connection connectionInfo                                                                 
                          -> (handlerParams -> connection -> connectionInfo -> m r) -> m r
          (bound at src/Data/ConnectionPool/Internal/ConnectionPool.hs:175:1)                                                       
    |                                                             
176 |     Pool.withResource _resourcePool (uncurry (f _handlerParams))                                                              
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                              

/var/stackage/work/unpack-dir/unpacked/connection-pool-0.2.2-59172d8e2bc6c82e06991a9601f932ad6f3dfd0348cea0cce0ae60b16dc54ebd/src/Da
ta/ConnectionPool/Internal/ConnectionPool.hs:188:5: error:
    • Couldn't match type ‘m’ with ‘IO’                           
      Expected: m (Maybe r)                                       
        Actual: IO (Maybe r)                                      
      ‘m’ is a rigid type variable bound by                       
        the type signature for:                                   
          tryWithConnection :: forall (m :: * -> *) handlerParams connection                                                        
                                      connectionInfo r.                                                                             
                               MonadBaseControl IO m =>                                                                             
                               ConnectionPool handlerParams connection connectionInfo                                               
                               -> (handlerParams -> connection -> connectionInfo -> m r)
                               -> m (Maybe r)                                                                                       
        at src/Data/ConnectionPool/Internal/ConnectionPool.hs:(182,1)-(186,18)                                                      
    • In the expression:                                          
        Pool.tryWithResource _resourcePool (uncurry (f _handlerParams))                                                             
      In an equation for ‘tryWithConnection’:                                                                                       
          tryWithConnection ConnectionPool {..} f                                                                                   
            = Pool.tryWithResource _resourcePool (uncurry (f _handlerParams))                                                       
    • Relevant bindings include                                   
        f :: handlerParams -> connection -> connectionInfo -> m r                                                                   
          (bound at src/Data/ConnectionPool/Internal/ConnectionPool.hs:187:38)                                                      
        tryWithConnection :: ConnectionPool                                                                                         
                               handlerParams connection connectionInfo                                                              
                             -> (handlerParams -> connection -> connectionInfo -> m r)
                             -> m (Maybe r)                                                                                         
          (bound at src/Data/ConnectionPool/Internal/ConnectionPool.hs:187:1)                                                       
    |                                                             
188 |     Pool.tryWithResource _resourcePool (uncurry (f _handlerParams))                                                           
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                           
```
